version: '2'

services:
  traefik:
    image: traefik
    restart: always
    ports:
      - 80:80
    expose:
      - 8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/traefik.toml
    container_name: traefik
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host:dashboard.localhost.hacknlove.org"
      traefik.frontend.auth.basic: "" #htpasswd -nb username password
      traefik.port: 8080

networks:
  web:
    external: true
